[project]
name = "singbox-config-convert"
version = "0.1.0"
description = ""
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "uvicorn",
    "httpx[http2]",
    "h2",
    "jinja2",
    "PyYAML",
    "orjson",
    "paramiko",
    "scp",
    "chardet",
    "python-multipart",
    "pybase64"
]

[tool.setuptools]
py-modules = ["main", "tool", "gh_proxy_helper"]
packages = ["api", "parsers"]

[build-system]
requires = ["setuptools>=81.0"]
build-backend = "setuptools.build_meta"